version: '3'

services:
  webserver:
    container_name: php-apache_server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - backend-network

  db:
    container_name: mysql_server
    image: mysql:latest
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
