# Основа
FROM ubuntu:latest

RUN apt-get update

# сервисы
RUN apt-get install -y apache2 apache2-utils curl gnupg wget
RUN a2enmod rewrite
RUN a2enmod lbmethod_byrequests

# установка локального времени
ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y git python3 perl \
	php nano

# php пакеты
RUN apt-get install -y \
	php-pdo php-pdo-mysql \
	php-mbstring php-tokenizer \
	php-xml php-simplexml php-zip \
	php-opcache php-iconv php-intl \
	php-json php-gd php-ctype php-oauth \
	php-apcu php-imagick php-xdebug \
	php-memcached php-ftp php-imap \
	php-curl iputils-ping

# Обновляем индекс после установки всех пакетов
RUN apt-get update

COPY --from=composer /usr/bin/composer /usr/bin/composer

# открываем 80 порт
EXPOSE 80

# Добавим в контейнер файл php.ini, расположим его в стандартном для Ubuntu месте
ADD ./docker/conf/php/php.ini /etc/php/8.1/apache2/php.ini

ADD ./docker/conf/php/xdebug.ini /etc/php/8.1/mods-available/xdebug.ini

ADD ./docker/conf/apache/apache2.conf /etc/apache2/apache2.conf

# Удаляем ненужные файлы, которые предоставит Ubuntu
RUN rm -R /etc/apache2/sites-enabled/* /etc/apache2/sites-available/* /var/www/*

# Добавляем свои файлы
ADD ./docker/conf/apache/module_configs/greeting.conf /etc/apache2/sites-enabled/greeting.conf
ADD ./docker/conf/apache/module_configs/phpmyadmin.conf /etc/apache2/sites-enabled/phpmyadmin.conf

# Указываем рабочую директорию
WORKDIR /var/wwww

# Запускаем процесс apache2 на переднем плане
# Пока живет этот процесс - живет и контейнер
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]